# Generated by Django 5.2 on 2025-05-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_tags_alter_course_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
